//User
export const FETCH_USER: string = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

//Home Carousel
export const GET_CAROUSEL = 'GET_CAROUSEL'
export const GET_CAROUSEL_SUCCESS = 'GET_CAROUSEL_SUCCESS'
export const GET_CAROUSEL_ERROR = 'GET_CAROUSEL_ERROR'

//Home Board
export const TOGGLE_HOME_BOARD = 'TOGGLE_HOME_BOARD'

//SideBar
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

//Movie
export const GET_MOVIE_PLAY_DATA = 'GET_MOVIE_PLAY_DATA'
export const GET_MOVIE_PLAY_DATA_SUCCESS = 'GET_MOVIE_PLAY_DATA_SUCCESS'
export const GET_MOVIE_DETAILS_DATA = 'GET_MOVIE_DETAILS_DATA'
export const GET_MOVIE_DETAILS_DATA_SUCCESS = 'GET_MOVIE_DETAILS_DATA_SUCCESS'

//Category
export const GET_CATEGORY_DATA = 'GET_CATEGORY_DATA'
export const GET_CATEGORY_DATA_SUCCESS = 'GET_CATEGORY_DATA_SUCCESS'
