//User
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

//Home Carousel
export const GET_CAROUSEL = 'GET_CAROUSEL'
export const GET_CAROUSEL_SUCCESS = 'GET_CAROUSEL_SUCCESS'
export const GET_CAROUSEL_ERROR = 'GET_CAROUSEL_ERROR'

